services:
  cart:
    container_name: cart
    image: kp3073/cart:15
    environment:
      REDIS_HOST: redis
      CATALOGUE_HOST: catalogue
      depends_on:
      - catalogue
      - redis
  catalogue:
    container_name: catalogue
    image: kp3073/catalogue:16
    environment:
      MONGO_URL: "mongodb://mongodb:27017/catalogue"
    depends_on:
    - mongodb
  frontend:
    container_name: frontend
    image: kp3073/frontend:39
    ports:
    - "80:80"
    depends_on:
    - catalogue
  mongodb:
    container_name: mongodb
    image: kp3073/mongodb:34
    cart:
      container_name: cart
      image: kp3073/cart:15
      environment:
        REDIS_HOST: redis
        CATALOGUE_HOST: catalogue
      depends_on:
      - catalogue
      - redis
  #  mysql:
  #    container_name: mysql
  #    image: kp3073/mysql:19
  #    environment:
  #      MYSQL_ROOT_PASSWORD: "root123"
  #  payment:
  #    container_name: payment
  #    image: kp3073/payment:20
  
  redis:
    image: redis
    container_name: redis
  user:
    container_name: user
    image: kp3073/user:26
    environment:
      MONGO_URL: "mongodb://mongodb:27017/users"
      REDIS_HOST: redis
    depends_on:
    - mongodb
    - redis  