services:
  frontend:
    container_name: frontend
    image: kp3073/frontend:24
    ports:
    - "80:80"
    depends_on:
    - catalogue
  catalogue:
    container_name: catalogue
    image: kp3073/catalogue:16