services:
  cart:
    container_name: cart
    image: kp3073/cart:15
    environment:
      REDIS_HOST: redis
      CATALOGUE_HOST: catalogue
    depends_on:
    - catalogue
    - redis
  catalogue:
    container_name: catalogue
    image: kp3073/catalogue:16
    environment:
      MONGO_URL: "mongodb://mongodb:27017/catalogue"
    depends_on:
    - mongodb
  frontend:
    container_name: frontend
    image: kp3073/frontend:41
    ports:
    - "80:80"
    depends_on:
    - catalogue
  mongodb:
    image: kp3073/mongodb:34
    container_name: mongodb
  redis:
    image: redis
    container_name: redis
  #  mysql:
  #    container_name: mysql
  #    image: kp3073/mysql:19
  #    environment:
  #      MYSQL_ROOT_PASSWORD: "root123"
  #  payment:
  #    container_name: payment
  #    image: kp3073/payment:20
  users:
    container_name: users
    image: kp3073/users:40
    environment:
      MONGO_URL: "mongodb://mongodb:27017/users"
      REDIS_HOST: redis
    depends_on:
    - mongodb
    - redis
